"""
config.py — Central path configuration for the gaze-aware fMRI encoding pipeline.

Set BASE_DIR to the root of your data directory. All other paths are derived
from it automatically. Intermediate directories are created if they do not exist.
"""

import os

# ============================================================
# SET THIS: root directory where all data will be stored/read
# ============================================================
BASE_DIR = '/path/to/your/data'

# ============================================================
# Raw inputs (user must provide)
# ============================================================

# Remodnav eye-tracking event files: {sub}-run{run}.tsv
REMODNAV_DIR        = os.path.join(BASE_DIR, 'raw', 'remodnav')

# Movie stimulus frames, organised as Run{run}/frame{N}.jpg
FRAMES_DIR          = os.path.join(BASE_DIR, 'raw', 'frames')

# Preprocessed fMRI data: normalized_masked_concat_movie_{sub}.npy
FMRI_DIR            = os.path.join(BASE_DIR, 'raw', 'fmri')

# Population receptive field estimates: no_threshold_prf_estimates_array_cover10_{sub}.npy
# Only required for precision_gaze_and_prf.py
PRF_DIR             = os.path.join(BASE_DIR, 'raw', 'prf')

# ============================================================
# Intermediate outputs (generated by the pipeline)
# ============================================================

# Output of remodnav_frame_selection.py
# Stores per-subject fixation events and frame indices per run
FIXATIONS_DIR       = os.path.join(BASE_DIR, 'derivatives', 'fixations')

# Output of frames_to_vgg19features.py
# Stores VGG-19 features indexed by run and layer
VGG_BY_RUN_DIR      = os.path.join(BASE_DIR, 'derivatives', 'vgg_features', 'by_run')

# Output of remodnav_save_features_by_subs.py
# Stores VGG-19 features indexed by subject and layer
VGG_BY_SUB_DIR      = os.path.join(BASE_DIR, 'derivatives', 'vgg_features', 'by_sub')

# Output of form_and_save_hyperlayers.py
# Stores the concatenated hyperlayer feature maps per subject
HYPERLAYERS_DIR     = os.path.join(BASE_DIR, 'derivatives', 'vgg_features', 'hyperlayers')

# ============================================================
# Results (output of encoding model scripts)
# ============================================================

RESULTS_DIR         = os.path.join(BASE_DIR, 'derivatives', 'results')

# ============================================================
# Analysis inputs (required for analysis.py / figure generation)
# ============================================================

# AAL atlas mask resampled to functional space:
#   aal_mask_downsampled_with_func_mni_3iso_nan_bb.nii
AAL_MASK            = os.path.join(BASE_DIR, 'raw', 'atlas', 'aal_mask_downsampled_with_func_mni_3iso_nan_bb.nii')

# Any single preprocessed functional NIfTI used as resampling reference:
#   e.g. sub-01_movie_run-1_hyperaligned.nii
REF_NIFTI           = os.path.join(BASE_DIR, 'raw', 'atlas', 'ref_func.nii')

# Precomputed gaze distribution heatmaps and baseline model spatial weights.
# These are pkl files exported from the original Colab notebook:
#   all_subs_gaze_dists.pkl            — per-subject gaze density maps (7x16)
#   all_subs_weights_over_space.pkl    — per-subject baseline model weights over space (7x16xV)
WEIGHTS_DIR         = os.path.join(BASE_DIR, 'derivatives', 'weights_and_gaze')

# Output directory for saved figures
FIGURES_DIR         = os.path.join(BASE_DIR, 'derivatives', 'figures')

# ============================================================
# Create all directories if they don't exist
# ============================================================

_dirs = [
    REMODNAV_DIR,
    FRAMES_DIR,
    FMRI_DIR,
    PRF_DIR,
    FIXATIONS_DIR,
    VGG_BY_RUN_DIR,
    VGG_BY_SUB_DIR,
    HYPERLAYERS_DIR,
    RESULTS_DIR,
    os.path.join(BASE_DIR, 'raw', 'atlas'),
    WEIGHTS_DIR,
    FIGURES_DIR,
]

for _d in _dirs:
    os.makedirs(_d, exist_ok=True)
